name: Deploy via SSH

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 🛎
        uses: actions/checkout@v4

      - name: Install SSH key of bastion 🔑
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY_BASTION }}
          name: id_rsa_bastion
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          config: |
            Host bastion
              HostName ${{ secrets.JUMP_HOST }}
              User ${{ secrets.JUMP_USER }}
              IdentityFile ~/.ssh/id_rsa_bastion

      - name: Install SSH key of target 🔑
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY_TARGET }}
          name: id_rsa_target
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          config: |
            Host target
              HostName ${{ secrets.TARGET_HOST }}
              User ${{ secrets.TARGET_USER }}
              IdentityFile ~/.ssh/id_rsa_target
              ProxyCommand ssh -W %h:%p bastion

      - name: Deploy to server 📡
        run: |
          ssh target "cd ${{ secrets.DEPLOY_PATH }} && git pull origin master && npm ci && npx prisma generate && npx prisma migrate deploy && npm run build && pm2 restart 99cents"

      - name: Clear Cloudflare cache 🆑
        uses: Cyb3r-Jak3/action-cloudflare-cache@v3.0.0
        with:
          zone: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Notify to Telegram
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            ${{ job.status == 'success' && '✅ *Deploy 99cents.one SUCCESS*' || '❌ *Deploy 99cents.one FAILED*' }}

            *Repo:* `${{ github.repository }}`
            *Branch:* `${{ github.ref_name }}`
            *Commit:* `${{ github.sha }}`
            *Author:* `${{ github.actor }}`
            *Message:* _${{ github.event.head_commit.message }}_
            [🔗 Open workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            [🔗 See changes](${{ github.server_url }}/${{ github.repository }}/commit/${{github.sha}})
